pre-commit:
  parallel: true
  commands:
    branch-name:
      run: |
        branch_name=$(git symbolic-ref --short HEAD)
        if ! echo "$branch_name" | grep -Eq '^[0-9]+/[a-z0-9-]+$'; then
          echo "Branch name '$branch_name' does not match the required pattern: [id]/[task-name] (e.g., 100/configure-github)"
          exit 1
        fi
    lint:
      run: pnpm lint
