name: Pull Request Build

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - '**/*.json'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.mjs'
      - '**/*.astro'
      - 'astro.config.json'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup
        uses: ./.github/shared/setup

      - name: Run build
        run: pnpm build
