name: Pull Request Build

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - '**/*.json'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.mjs'
      - '**/*.astro'
      - 'astro.config.json'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup
        uses: ./.github/shared/setup

      - name: Run build
        run: pnpm build
