name: Pull Request Check Types

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**/*.astro'
      - '**/*.ts'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  check-types:
    name: Check Types
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/shared/setup

      - name: Run type checks
        run: pnpm astro check
