name: Nuclei DAST Scan

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  dast:
    name: Run Nuclei DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup
        uses: ./.github/shared/setup

      - name: Start Astro Preview
        run: pnpm run preview &

      - name: Nuclei Scan (Local)
        uses: projectdiscovery/nuclei-action@cc153d0541e1adf8a42bbe31c0a4fb2376147538 # v3.1.1
        with:
          args: '-u http://localhost:4321 -severity low,medium,high,critical'
