name: Nuclei DAST Scan

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  dast:
    name: Run Nuclei DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup
        uses: ./.github/shared/setup

      - name: Start Astro Preview
        run: pnpm run preview &

      - name: Nuclei Scan (Local)
        uses: projectdiscovery/nuclei-action@cc153d0541e1adf8a42bbe31c0a4fb2376147538 # v3.1.1
        with:
          args: '-u http://localhost:4321 -severity low,medium,high,critical'
