name: Pull Request Dependencies Validation

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - '.dependency-cruiser.mjs'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  validate-dependencies:
    name: Validate Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/shared/setup

      - name: Run dependency checks
        run: pnpm depcruise
