name: Pull Request Lint

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - '**/*.json'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.mjs'
      - '**/*.astro'
      - 'biome.json'
      - 'pnpm-lock.yaml'
      - 'package.json'
jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/shared/setup

      - name: Run Biome
        run: pnpm lint

      - name: Run Prettier
        run: pnpm prettier --check .
