name: Pull Request Unit Tests

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**/*.ts'
      - 'vitest.config.ts'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup
        uses: ./.github/shared/setup

      - name: Run unit tests
        run: pnpm unit
